name: Linux CI

on:
  push:
    branches: [ "devel", "master" ]
  pull_request:
    branches: [ "devel", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  DRUMSTICKNAME: DrumstickV2
  DRUMSTICK_LOCATION: ${{github.workspace}}/DrumstickV2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64", "aarch64"]
        include:
          - { icon: '🟥', arch: "x86_64", os: "ubuntu-26.04", triplet: "x64-linux-release" }
          - { icon: '🟩', arch: "aarch64", os: "ubuntu-26.04-arm", triplet: "arm64-linux-release" }
    runs-on: ${{ matrix.os }}
    name: '${{ matrix.icon }} Linux ${{ matrix.arch }}'

    steps:
    - uses: actions/checkout@v7

    - name: '${{ matrix.icon }} Download Drummstick'
      uses: dawidd6/action-download-artifact@v21
      with:
        name: ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz
        github_token: ${{secrets.GH_PAT}}
        repo: pedrolcl/drumstick
        allow_forks: false
        workflow: linux.yml
        skip_unpack: true

    - name: '${{ matrix.icon }} Extract Drumstick'
      run: |
        mv ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz.zip ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz
        tar xvzf ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz

    - name: '${{ matrix.icon }} Install Qt'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.1'
        modules: qt5compat

    - name: '${{ matrix.icon }} Install Dependencies'
      run: sudo apt-get update && sudo apt-get install -yq pkg-config libasound2-dev

    - name: '${{ matrix.icon }} Configure CMake'
      id: configuration
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_INSTALL_LIBDIR=lib
        -DCMAKE_PREFIX_PATH="${{env.DRUMSTICK_LOCATION}}"
        -DCMAKE_INSTALL_RPATH="\$ORIGIN/../lib"
        -DWORKDIR=${{github.workspace}}
        -DBUILD_DOCS=OFF

    - name: '${{ matrix.icon }} Build'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Install'
      env:
        DESTDIR: ${{github.workspace}}/wrk2mid-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppDir
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Archive'
      env:
        INSTALL_LOCATION: wrk2mid-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppDir
      run: tar -cvzf ${{env.INSTALL_LOCATION}}.tar.gz ${{env.INSTALL_LOCATION}}

    - name: '${{ matrix.icon }} Upload Archive'
      env:
        INSTALL_LOCATION: wrk2mid-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppDir
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.INSTALL_LOCATION}}
        path: ${{github.workspace}}/${{env.INSTALL_LOCATION}}.tar.gz
        retention-days: 90
        overwrite: true
        archive: false

    - name: '${{ matrix.icon }} Upload AppImage'
      env:
        INSTALL_LOCATION: wrk2mid-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppImage
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.INSTALL_LOCATION}}
        path: ${{github.workspace}}/${{env.INSTALL_LOCATION}}
        retention-days: 90
        overwrite: true
        archive: false
