name: Windows MSYS2 CI

on:
  push:
    branches: [ "devel", "master" ]
  pull_request:
    branches: [ "devel", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  DRUMSTICK: DrumstickV2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟦', sys: mingw64,    os: windows-latest }
          - { icon: '🟩', sys: clangarm64, os: windows-11-arm }
    runs-on: ${{ matrix.os }}
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        release: true
        update: true
        msystem: ${{matrix.sys}}
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          qt6-base:p
          qt6-5compat:p

    - uses: actions/checkout@v7

    - name: '${{ matrix.icon }} Download Drumstick artifact'
      uses: dawidd6/action-download-artifact@v21
      with:
        name: ${{env.DRUMSTICK}}-msys2-${{ matrix.sys }}.tar.gz
        github_token: ${{secrets.GH_PAT}}
        repo: pedrolcl/drumstick
        allow_forks: false
        workflow: win-msys.yml
        branch: devel
        skip_unpack: true

    - name: '${{ matrix.icon }} Extract downloaded files'
      run: |
        mv ${{env.DRUMSTICK}}.tar.gz.zip ${{env.DRUMSTICK}}.tar.gz
        tar xvzf ${{env.DRUMSTICK}}.tar.gz

    - name: '${{ matrix.icon }} Configure CMake'
      run: cmake -B ${{github.workspace}}/build
        -DBUILD_DOCS=OFF
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_PREFIX_PATH="${{env.DRUMSTICK}}"

    - name: '${{ matrix.icon }} Build'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
